export const CHANGE_ITEM_FOR_QUALITY_MANAGEMENT_LINE_CHART = 'CHANGE_ITEM_FOR_QUALITY_MANAGEMENT_LINE_CHART';

export function selectItem() {
  return {
    type: CHANGE_ITEM_FOR_QUALITY_MANAGEMENT_LINE_CHART,
  };
}