export const CHANGE_ITEM_FOR_QUALITY_MANAGEMENT_BAR_CHART = 'CHANGE_ITEM_FOR_QUALITY_MANAGEMENT_BAR_CHART';

export function selectItem() {
  return {
    type: CHANGE_ITEM_FOR_QUALITY_MANAGEMENT_BAR_CHART,
  };
}