export const CHANGE_ITEM_FOR_QUALITY_MANAGEMENT_PIE_CHART = 'CHANGE_ITEM_FOR_QUALITY_MANAGEMENT_PIE_CHART';

export function selectItem() {
  return {
    type: CHANGE_ITEM_FOR_QUALITY_MANAGEMENT_PIE_CHART,
  };
}