export const CHANGE_ITEM_FOR_COST_REDUCTION_PIE_CHART = 'CHANGE_ITEM_FOR_COST_REDUCTION_PIE_CHART';

export function selectItem() {
  return {
    type: CHANGE_ITEM_FOR_COST_REDUCTION_PIE_CHART,
  };
}